# Generated by Django 6.0.4 on 2026-07-16 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_academics', '0017_alter_homework_id_alter_leavebalance_id_and_more'),
        ('education_students', '0006_student_birth_form_id_student_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(choices=[('affective', 'Affective Domain'), ('psychomotor', 'Psychomotor Domain')], default='affective', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('max_rating', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_type', models.CharField(choices=[('incident', 'Incident'), ('meeting', 'Meeting'), ('counselling', 'Counselling')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('action_taken', models.TextField(blank=True, default='')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('outcome', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='education_academics.schoolclass')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='education_students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='education_academics.teacher')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BehaviourRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('affective', 'Affective Domain'), ('psychomotor', 'Psychomotor Domain')], default='affective', max_length=20)),
                ('term', models.CharField(default='first', max_length=20)),
                ('academic_year', models.CharField(default='2026-2027', max_length=20)),
                ('ratings', models.JSONField(blank=True, default=dict)),
                ('comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_ratings', to='education_academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_ratings', to='education_students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_ratings', to='education_academics.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'class_ref', 'domain', 'term', 'academic_year')},
            },
        ),
    ]
