# Generated by Django 6.0.4 on 2026-07-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0001_initial'),
        ('education_academics', '0017_alter_homework_id_alter_leavebalance_id_and_more'),
        ('education_students', '0006_student_birth_form_id_student_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='behaviourrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='behaviourrating',
            name='ai_parent_rec',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='behaviourrating',
            name='ai_teacher_rec',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='behaviourrating',
            name='month',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='behaviourrating',
            name='not_observed',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='behaviourrating',
            name='plans',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='behaviourrating',
            name='rewards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='observation',
            name='parent_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observation',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='behaviourrating',
            unique_together={('student', 'class_ref', 'domain', 'term', 'academic_year', 'month')},
        ),
    ]
