# Generated by Django 6.0.4 on 2026-05-16 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_code', models.CharField(db_index=True, help_text='Three-letter code, e.g. SPR, GRD, RIV', max_length=3, unique=True)),
                ('school_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated, e.g. SPR-001', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(db_index=True, max_length=100, unique=True)),
                ('email_domain', models.CharField(blank=True, help_text='Optional email domain for auto-tenant routing', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'tenants_school',
                'ordering': ['tenant_code'],
                'indexes': [models.Index(fields=['subdomain'], name='tenants_sch_subdoma_b4a354_idx'), models.Index(fields=['is_active', 'tenant_code'], name='tenants_sch_is_acti_a5e00d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student'), ('accountant', 'Accountant')], default='staff', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('rbac_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_memberships', to='rbac_models.role')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core_tenants.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenants_membership',
                'indexes': [models.Index(fields=['user', 'is_active'], name='tenants_mem_user_id_7586b1_idx'), models.Index(fields=['school', 'role'], name='tenants_mem_school__4e6806_idx')],
                'unique_together': {('user', 'school')},
            },
        ),
    ]
