# Generated by Django 5.2.17 on 2026-09-25 09:26

import django.db.models.deletion
import services.core.tenants.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_tenants", "0003_assign_unowned_rows"),
        ("education_academics", "0026_guess_grade_levels"),
        ("education_exams", "0004_examschedule_examregistration"),
        ("education_students", "0013_backfill_enrollments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percent of the term grade",
                        max_digits=5,
                    ),
                ),
                (
                    "drop_lowest",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Ignore this many lowest scores"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gradebook_categories",
                        to="education_academics.classsubject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "points_possible",
                    models.DecimalField(decimal_places=2, default=100, max_digits=7),
                ),
                ("counts_toward_grade", models.BooleanField(default=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Students and parents can see it and its scores",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gradebook_assignments",
                        to="education_academics.classsubject",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gradebook_assignment",
                        to="education_exams.exam",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for every section",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education_academics.section",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="education_academics.term",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="education_gradebook.category",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "created_at"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GradingScale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("letter", "Letter grades"),
                            ("percentage", "Percentages only"),
                            ("standards", "Standards levels (4–1)"),
                        ],
                        default="letter",
                        max_length=12,
                    ),
                ),
                (
                    "passing_percent",
                    models.DecimalField(decimal_places=2, default=60, max_digits=5),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GradeBand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=20)),
                ("min_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "gpa_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bands",
                        to="education_gradebook.gradingscale",
                    ),
                ),
            ],
            options={
                "ordering": ["-min_percent"],
            },
        ),
        migrations.CreateModel(
            name="ReportCardRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("released_at", models.DateTimeField(auto_now_add=True)),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="education_academics.schoolclass",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="education_academics.term",
                    ),
                ),
            ],
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReportComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="education_academics.classsubject",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_comments",
                        to="education_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="education_academics.term",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("graded", "Graded"),
                            ("missing", "Missing"),
                            ("excused", "Excused"),
                            ("late", "Late"),
                            ("incomplete", "Incomplete"),
                        ],
                        default="graded",
                        max_length=12,
                    ),
                ),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="education_gradebook.assignment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gradebook_scores",
                        to="education_students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grade_level", models.SmallIntegerField(blank=True, null=True)),
                ("code", models.CharField(blank=True, default="", max_length=40)),
                ("description", models.CharField(max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standards",
                        to="education_academics.subject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["code", "description"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.AddField(
            model_name="assignment",
            name="standards",
            field=models.ManyToManyField(
                blank=True,
                related_name="assignments",
                to="education_gradebook.standard",
            ),
        ),
        migrations.CreateModel(
            name="StandardRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="education_gradebook.standard",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_ratings",
                        to="education_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_ratings",
                        to="education_academics.term",
                    ),
                ),
            ],
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("class_subject", "name"), name="uniq_gradebook_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportcardrelease",
            constraint=models.UniqueConstraint(
                fields=("term", "school_class"), name="uniq_report_release"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportcomment",
            constraint=models.UniqueConstraint(
                fields=("student", "class_subject", "term"), name="uniq_report_comment"
            ),
        ),
        migrations.AddConstraint(
            model_name="score",
            constraint=models.UniqueConstraint(
                fields=("assignment", "student"), name="uniq_score"
            ),
        ),
        migrations.AddConstraint(
            model_name="standardrating",
            constraint=models.UniqueConstraint(
                fields=("student", "standard", "term"), name="uniq_standard_rating"
            ),
        ),
    ]
