# Generated by Django 5.2.17 on 2026-09-25 23:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_tenants", "0003_assign_unowned_rows"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SignInEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=255)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Signed in"),
                            ("failed", "Wrong password"),
                            ("locked", "Blocked: too many wrong passwords"),
                            ("disabled", "Blocked: account switched off"),
                        ],
                        max_length=12,
                    ),
                ),
                ("method", models.CharField(default="password", max_length=20)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sign_in_events",
                        to="core_tenants.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sign_in_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "created_at"],
                        name="core_securi_school__650ea0_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="core_securi_user_id_f5f04e_idx",
                    ),
                ],
            },
        ),
    ]
