# Generated by Django 6.0.4 on 2026-05-06 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_academics', '0002_classsubject_subject_delete_course_delete_program_and_more'),
        ('education_students', '0003_add_last_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('midterm', 'Mid Term Examination'), ('final', 'Final Term Examination'), ('quiz', 'Quiz'), ('test', 'Unit Test'), ('assignment', 'Assignment')], max_length=20)),
                ('total_marks', models.IntegerField()),
                ('passing_marks', models.IntegerField()),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('academic_year', models.CharField(default='2026-2027', max_length=20)),
                ('term', models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term')], default='first', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='education_academics.schoolclass')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education_academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='education_academics.subject')),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('grade', models.CharField(choices=[('A+', 'A+ (90-100%)'), ('A', 'A (80-89%)'), ('B+', 'B+ (70-79%)'), ('B', 'B (60-69%)'), ('C+', 'C+ (50-59%)'), ('C', 'C (40-49%)'), ('D', 'D (33-39%)'), ('F', 'F (Below 33%)')], editable=False, max_length=2)),
                ('is_pass', models.BooleanField(default=False, editable=False)),
                ('remarks', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='education_exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='education_students.student')),
            ],
            options={
                'ordering': ['-exam__exam_date'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
