# Generated by Django 6.0.4 on 2026-05-03 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=120)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_number', models.CharField(blank=True, max_length=50)),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('is_pass', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('entered_by', models.CharField(blank=True, max_length=100)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='education_exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='education_students.student')),
            ],
            options={
                'ordering': ['-entered_at'],
                'unique_together': {('exam', 'student_id')},
            },
        ),
    ]
