# Generated by Django 6.0.4 on 2026-05-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_add_tenant_nullable'),
        ('education_exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core_tenants.school'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core_tenants.school'),
        ),
    ]
