# Generated by Django 5.2.17 on 2026-09-26 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ErrorGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("backend", "Server"), ("frontend", "Browser")],
                        max_length=10,
                    ),
                ),
                ("kind", models.CharField(max_length=120)),
                ("message", models.CharField(max_length=500)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True, db_index=True)),
                ("last_school", models.CharField(blank=True, max_length=255)),
                ("last_user", models.CharField(blank=True, max_length=255)),
                ("last_path", models.CharField(blank=True, max_length=300)),
                ("release", models.CharField(blank=True, max_length=60)),
                ("samples", models.JSONField(blank=True, default=list)),
                ("alerted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
    ]
