# Generated by Django 5.2.17 on 2026-09-25 21:08

import django.db.models.deletion
import services.core.tenants.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_tenants", "0003_assign_unowned_rows"),
        ("education_academics", "0026_guess_grade_levels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_id", models.CharField(max_length=64)),
                (
                    "course_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_report", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_links",
                        to="education_academics.schoolclass",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "course_id"), name="uniq_classroom_course"
                    )
                ],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("microsoft", "Microsoft 365 / Entra ID sign-in"),
                            ("google_classroom", "Google Classroom"),
                            ("email", "School email (SMTP)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("secret_blob", models.TextField(blank=True, default="")),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "provider"), name="uniq_integration_provider"
                    )
                ],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
    ]
