# Generated by Django 6.0.4 on 2026-07-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_db_scalability'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, help_text='Field-level diff: {field: {old, new}}', null=True),
        ),
    ]
