# Generated by Django 5.2.17 on 2026-09-25 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_auditlog_changes"),
        ("core_tenants", "0003_assign_unowned_rows"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="core_tenants.school",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("VIEW", "View"),
                    ("PERMISSION_DENIED", "Permission Denied"),
                    ("EXPORT", "Export"),
                    ("SECURITY", "Security"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["school", "timestamp"], name="audit_audit_school__c0fedb_idx"
            ),
        ),
    ]
