# Generated by Django 5.2.17 on 2026-09-26 03:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_billing", "0002_seed_plans"),
        ("core_tenants", "0003_assign_unowned_rows"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="ISO country code, e.g. GB, DE, PK",
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(default="VAT", max_length=30)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Percent, e.g. 20.00", max_digits=5
                    ),
                ),
                (
                    "exempt_with_tax_id",
                    models.BooleanField(
                        default=False,
                        help_text="Reverse charge: no tax when the school gives a tax ID",
                    ),
                ),
            ],
            options={
                "ordering": ["country"],
            },
        ),
        migrations.CreateModel(
            name="PlatformInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=20, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("period", "Subscription period"),
                            ("proration", "Upgrade difference"),
                        ],
                        default="period",
                        max_length=10,
                    ),
                ),
                ("plan_name", models.CharField(max_length=60)),
                ("billing_cycle", models.CharField(default="monthly", max_length=8)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_label", models.CharField(blank=True, max_length=30)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("tax_note", models.CharField(blank=True, max_length=200)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("paid", "Paid"), ("void", "Void")],
                        default="open",
                        max_length=6,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("due_date", models.DateField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("paid_via", models.CharField(blank=True, max_length=20)),
                ("payment_reference", models.CharField(blank=True, max_length=120)),
                ("bill_to", models.JSONField(blank=True, default=dict)),
                ("reminders", models.JSONField(blank=True, default=list)),
                ("stripe_session_id", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core_billing.plan",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_invoices",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-number"],
            },
        ),
    ]
