# Generated by Django 6.0.4 on 2026-05-04 07:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_grade', models.CharField(max_length=5)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factors', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='education_students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('academic', 'Academic Support'), ('attendance', 'Attendance Improvement'), ('financial', 'Financial Assistance'), ('behavioral', 'Behavioral Support')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_items', models.JSONField(default=list)),
                ('is_implemented', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='education_students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('factors', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='education_students.student')),
            ],
        ),
    ]
