# Generated by Django 6.0.4 on 2026-05-04 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicant_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('previous_institution', models.CharField(blank=True, max_length=200)),
                ('previous_qualification', models.CharField(blank=True, max_length=100)),
                ('previous_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('applying_for', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New Application'), ('review', 'Under Review'), ('interview', 'Interview Scheduled'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('program', models.CharField(max_length=100)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('documents_received', 'Documents Received'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('decision_pending', 'Decision Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='education_admissions.applicant')),
            ],
        ),
    ]
