# Generated by Django 6.0.4 on 2026-05-06 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_admissions', '0001_initial'),
        ('education_students', '0003_add_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='converted_to_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education_students.student'),
        ),
    ]
