# Generated by Django 5.2.17 on 2026-09-25 06:34

import django.db.models.deletion
import services.education.admissions.models
import uuid
from django.conf import settings
from django.db import migrations, models


def unique_tokens(apps, schema_editor):
    import secrets

    Application = apps.get_model('education_admissions', 'Application')
    for app in Application.objects.all().only('pk'):
        Application.objects.filter(pk=app.pk).update(tracking_token=secrets.token_urlsafe(24))


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0003_assign_unowned_rows"),
        ("education_admissions", "0002_school_tenant"),
        ("education_students", "0010_backfill_households"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="applicant",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="applicant",
            name="guardians",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="applicant",
            name="home_language",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="applicant",
            name="medical_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="applicant",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="applicant",
            name="sibling_at_school",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="applicant",
            name="special_needs",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="applicant",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="application",
            name="consents",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="application",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="signature_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="signature_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="application",
            name="signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="source",
            field=models.CharField(
                choices=[
                    ("office", "Entered by the office"),
                    ("online", "Online application"),
                ],
                default="office",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="tracking_token",
            field=models.CharField(
                db_index=True,
                default=services.education.admissions.models._tracking_token,
                editable=False,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="father_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="father_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="nationality",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("reviewing", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("waitlisted", "Waitlisted"),
                    ("enrolled", "Enrolled"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("doc_type", models.CharField(max_length=60)),
                ("file", models.FileField(upload_to="admissions/%Y/%m/")),
                (
                    "original_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="education_admissions.application",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("to_status", models.CharField(blank=True, default="", max_length=20)),
                ("note", models.TextField(blank=True, default="")),
                ("by_name", models.CharField(blank=True, default="", max_length=200)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="education_admissions.application",
                    ),
                ),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["at"],
            },
        ),
        migrations.CreateModel(
            name="ReEnrollmentCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True, default="")),
                ("closes_on", models.DateField(blank=True, null=True)),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReEnrollmentResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("pending", "No answer yet"),
                            ("returning", "Returning"),
                            ("not_returning", "Not returning"),
                            ("undecided", "Undecided"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "signature_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="education_admissions.reenrollmentcampaign",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reenrollments",
                        to="education_students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["student__full_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "student"), name="uniq_reenrollment_student"
                    )
                ],
            },
        ),
        migrations.RunPython(unique_tokens, migrations.RunPython.noop),
    ]
