# Generated by Django 5.2.17 on 2026-09-26 05:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisasterRecoveryPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("tier1", "Tier 1 - Critical (RTO: 4h, RPO: 1h)"),
                            ("tier2", "Tier 2 - Important (RTO: 8h, RPO: 4h)"),
                            ("tier3", "Tier 3 - Standard (RTO: 24h, RPO: 24h)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "recovery_time_objective_hours",
                    models.IntegerField(
                        help_text="Maximum acceptable downtime in hours"
                    ),
                ),
                (
                    "recovery_point_objective_hours",
                    models.IntegerField(
                        help_text="Maximum acceptable data loss in hours"
                    ),
                ),
                (
                    "backup_frequency_hours",
                    models.IntegerField(help_text="Backup frequency in hours"),
                ),
                (
                    "full_backup_day",
                    models.CharField(
                        default="Sunday",
                        help_text="Day of week for full backups",
                        max_length=20,
                    ),
                ),
                ("daily_backup_retention_days", models.IntegerField(default=30)),
                ("monthly_backup_retention_days", models.IntegerField(default=365)),
                ("yearly_backup_retention_days", models.IntegerField(default=2555)),
                ("enable_automatic_failover", models.BooleanField(default=False)),
                ("failover_timeout_minutes", models.IntegerField(default=30)),
                (
                    "notification_emails",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of emails to notify on restore",
                    ),
                ),
                (
                    "slack_webhook_url",
                    models.CharField(
                        blank=True,
                        help_text="Slack webhook for alerts",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Disaster Recovery Plans",
            },
        ),
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Backup"),
                            ("database", "Database Only"),
                            ("media", "Media Only"),
                            ("config", "Configuration Only"),
                            ("redis", "Redis Only"),
                            ("incremental", "Incremental Backup"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("verified", "Verified"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "backup_path",
                    models.CharField(
                        help_text="Path to backup file or directory", max_length=500
                    ),
                ),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="Size of backup in bytes", null=True
                    ),
                ),
                ("database_backed_up", models.BooleanField(default=True)),
                ("media_backed_up", models.BooleanField(default=True)),
                ("config_backed_up", models.BooleanField(default=False)),
                ("redis_backed_up", models.BooleanField(default=False)),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 checksum of backup",
                        max_length=256,
                        null=True,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retention_days",
                    models.IntegerField(
                        default=30, help_text="Days to retain this backup"
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("cleanup_completed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Detailed error information"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional backup metadata"
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-started_at"],
                        name="core_backup_status_d5ceab_idx",
                    ),
                    models.Index(
                        fields=["backup_type", "-started_at"],
                        name="core_backup_backup__b396b0_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="core_backup_expires_3ca912_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BackupRestoreLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "restore_type",
                    models.CharField(
                        choices=[
                            ("full", "Full System Restore"),
                            ("database", "Database Only"),
                            ("media", "Media Files Only"),
                            ("config", "Configuration Only"),
                            ("pitr", "Point-in-Time Recovery"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("validated", "Validated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "recovery_time",
                    models.DateTimeField(
                        blank=True, help_text="Target recovery time for PITR", null=True
                    ),
                ),
                (
                    "target_database",
                    models.CharField(
                        help_text="Target database name or environment", max_length=200
                    ),
                ),
                (
                    "target_environment",
                    models.CharField(
                        choices=[
                            ("dev", "Development"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        help_text="Target environment",
                        max_length=50,
                    ),
                ),
                (
                    "restored_records",
                    models.IntegerField(
                        blank=True, help_text="Number of records restored", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("validated", models.BooleanField(default=False)),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of validation errors if any",
                    ),
                ),
                (
                    "requested_by",
                    models.CharField(
                        help_text="User who requested restore", max_length=200
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source_backup",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restore_operations",
                        to="core_backup.backuplog",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-started_at"],
                        name="core_backup_status_fb6ddb_idx",
                    ),
                    models.Index(
                        fields=["target_environment", "-started_at"],
                        name="core_backup_target__8d1730_idx",
                    ),
                ],
            },
        ),
    ]
