# Generated by Django 6.0.5 on 2026-05-17 09:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0003_parentprofile_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('permission_denied', 'Permission Denied'), ('login', 'Login'), ('logout', 'Logout'), ('payment', 'Payment'), ('attendance', 'Attendance'), ('result', 'Result')], max_length=50)),
                ('module', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_name', models.CharField(blank=True, max_length=255)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'action'], name='core_accoun_user_id_528524_idx'), models.Index(fields=['module', 'created_at'], name='core_accoun_module_ad5788_idx')],
            },
        ),
    ]
