# Generated by Django 6.0.4 on 2026-06-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0004_auditlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_accoun_user_id_528524_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_accoun_module_ad5788_idx',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
