# Generated by Django 5.2.17 on 2026-09-24 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_accounts", "0005_remove_auditlog_core_accoun_user_id_528524_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("initial_password", models.CharField(blank=True, max_length=64)),
                ("changed_by_user", models.BooleanField(default=False)),
                ("issued_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_credential",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
