# Generated by Django 6.0.4 on 2026-05-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogArchive',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(max_length=32)),
                ('resource_type', models.CharField(blank=True, max_length=128)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('source_timestamp', models.DateTimeField(db_index=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'archive_audit_log',
            },
        ),
        migrations.CreateModel(
            name='NotificationArchive',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('recipient_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('source_created_at', models.DateTimeField(db_index=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'archive_notification',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecordArchive',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('course_id', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'archive_attendance_record',
                'indexes': [models.Index(fields=['student_id', 'date'], name='archive_att_student_3fcb35_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceArchive',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=50)),
                ('student_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField(db_index=True)),
                ('issue_date', models.DateField(db_index=True)),
                ('status', models.CharField(max_length=20)),
                ('partition_year', models.PositiveSmallIntegerField(db_index=True)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'archive_invoice',
                'indexes': [models.Index(fields=['partition_year', 'student_id'], name='archive_inv_partiti_5ab38e_idx')],
            },
        ),
    ]
