# Generated by Django 6.0.4 on 2026-05-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_finance', '0002_installmentplan_invoice_discount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionlog',
            old_name='new_value',
            new_name='new_values',
        ),
        migrations.RenameField(
            model_name='transactionlog',
            old_name='old_value',
            new_name='old_values',
        ),
    ]
