# Generated by Django 6.0.4 on 2026-05-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_finance', '0003_rename_new_value_transactionlog_new_values_and_more'),
        ('education_students', '0002_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['student', 'due_date'], name='education_f_student_9e95d4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='education_f_status_c42175_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='education_f_issue_d_4a6735_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='education_f_created_54e7c1_idx'),
        ),
    ]
