# Generated by Django 6.0.4 on 2026-05-16 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_finance', '0005_add_tenant_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa')], max_length=30)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('merchant_id', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('api_secret', models.CharField(blank=True, max_length=200)),
                ('api_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=200)),
                ('callback_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider'],
                'unique_together': {('provider', 'merchant_id')},
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('gateway_reference', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education_finance.paymentgatewayconfig')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='education_finance.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
