# Generated by Django 6.0.5 on 2026-05-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_finance', '0006_add_online_payment_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
