# Generated by Django 6.0.5 on 2026-05-18 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_finance', '0007_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(default='School Management System', max_length=255)),
                ('grace_period_days', models.PositiveIntegerField(default=7)),
                ('auto_send_reminders', models.CharField(choices=[('disabled', 'Disabled'), ('7_days_before', '7 Days Before'), ('3_days_before', '3 Days Before'), ('on_due_date', 'On Due Date')], default='disabled', max_length=30)),
                ('default_late_fee', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('academic_year', models.CharField(default='2026-2027', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tenant',
        ),
    ]
