# Generated by Django 6.0.4 on 2026-06-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_finance', '0008_financesettings_remove_invoice_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_month',
            field=models.DateField(blank=True, db_index=True, help_text='First day of the month this invoice belongs to (e.g. 2026-06-01)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Balance brought forward (B/F) from previous unpaid invoices', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='issued', max_length=20),
        ),
    ]
