# Generated by Django 6.0.4 on 2026-07-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_finance', '0009_add_opening_balance_invoice_month_partial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
