# Generated by Django 6.0.4 on 2026-07-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_finance', '0010_invoice_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('transport', 'Transport'), ('hostel', 'Hostel'), ('miscellaneous', 'Miscellaneous'), ('composite', 'Composite')], default='tuition', help_text='The category of charges billed on this invoice', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('carried_forward', 'Carried Forward')], default='issued', max_length=20),
        ),
    ]
