# Generated by Django 6.0.4 on 2026-07-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_finance', '0011_invoice_invoice_type_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancellation_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
