# Generated by Django 5.2.17 on 2026-09-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0002_backfill_default_tenant"),
        ("education_finance", "0013_add_ledger_salary_weekday_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounthead",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="financesettings",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="installmentplan",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="latefeerule",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="paymentgatewayconfig",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="transactionlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="weekdayconfig",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AlterField(
            model_name="accounthead",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="weekdayconfig",
            name="day_code",
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name="accounthead",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_accounthead_code_per_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="weekdayconfig",
            constraint=models.UniqueConstraint(
                fields=("tenant", "day_code"),
                name="uniq_weekdayconfig_day_code_per_school",
            ),
        ),
    ]
