# Generated by Django 5.2.17 on 2026-09-25 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0003_assign_unowned_rows"),
        ("education_finance", "0014_school_tenant"),
        ("education_students", "0010_backfill_households"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="paymentgatewayconfig",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="installmentplan",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("biweekly", "Every two weeks"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("credit_card", "Credit Card"),
                    ("cheque", "Cheque"),
                    ("online", "Online Payment"),
                    ("account_credit", "Account credit"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentgatewayconfig",
            name="provider",
            field=models.CharField(
                choices=[
                    ("jazzcash", "JazzCash"),
                    ("easypaisa", "Easypaisa"),
                    ("stripe", "Stripe (cards, Apple Pay, Google Pay)"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("jazzcash", "JazzCash"),
                    ("easypaisa", "Easypaisa"),
                    ("stripe", "Stripe (cards, Apple Pay, Google Pay)"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentgatewayconfig",
            unique_together={("tenant", "provider", "merchant_id")},
        ),
        migrations.CreateModel(
            name="AccountCredit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("overpayment", "Overpayment"),
                            ("goodwill", "Credit given by the school"),
                            ("refund", "Refund kept as credit"),
                            ("applied", "Applied to an invoice"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="education_students.household",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education_finance.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education_finance.payment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_credits",
                        to="education_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("original", "Back to the original payment method"),
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank transfer"),
                            ("account_credit", "Kept as account credit"),
                        ],
                        default="original",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "gateway_reference",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="education_finance.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
