# Generated by Django 6.0.4 on 2026-05-09 20:42

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0001_initial'),
        ('education_students', '0002_student_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('capacity', models.IntegerField(default=30)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=5)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-max_percentage'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('order', models.IntegerField(default=0)),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('qualifications', models.JSONField(blank=True, default=list)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('experience_years', models.IntegerField(default=0)),
                ('joining_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('is_break', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.academicyear')),
            ],
            options={
                'ordering': ['period_number'],
                'unique_together': {('academic_year', 'period_number')},
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_hours', models.IntegerField(default=0)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.academicyear')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='education_academics.classsubject')),
            ],
            options={
                'unique_together': {('class_subject', 'academic_year', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SyllabusSubTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='education_academics.syllabustopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('book', 'Book'), ('reference', 'Reference Material'), ('video', 'Video'), ('website', 'Website'), ('document', 'Document'), ('software', 'Software'), ('other', 'Other')], max_length=20)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='education_academics.syllabus')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='education_academics.syllabustopic')),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('estimated_hours', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='education_academics.syllabus')),
            ],
            options={
                'ordering': ['order', 'unit_number'],
            },
        ),
        migrations.AddField(
            model_name='syllabustopic',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='education_academics.syllabusunit'),
        ),
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('behavior', 'Behavior'), ('progress', 'Progress'), ('concern', 'Concern')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.db.models.functions.datetime.Now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.classsubject')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education_students.student')),
                ('syllabus_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education_academics.syllabustopic')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentWeightage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weightage_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.academicyear')),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.assessmenttype')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightages', to='education_academics.classsubject')),
            ],
            options={
                'unique_together': {('class_subject', 'assessment_type', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentTopicProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_help', 'Needs Help')], default='not_started', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('feedback', models.TextField(blank=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.academicyear')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.classsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_students.student')),
                ('syllabus_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.syllabustopic')),
            ],
            options={
                'unique_together': {('student', 'syllabus_topic', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('resources_needed', models.JSONField(blank=True, default=list)),
                ('homework', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.classsubject')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.period')),
                ('syllabus_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.syllabustopic')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'class_subject', 'date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.academicyear')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='education_academics.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'day_of_week', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=True)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.academicyear')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='education_academics.classsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='education_academics.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'class_subject', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.academicyear')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.classsubject')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.classroom')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.period')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education_academics.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.teacher')),
            ],
            options={
                'unique_together': {('class_subject', 'day_of_week', 'period', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='TopicCoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverage_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('review', 'Under Review')], default='not_started', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.academicyear')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.classsubject')),
                ('syllabus_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.syllabustopic')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_academics.teacher')),
            ],
            options={
                'unique_together': {('syllabus_topic', 'class_subject', 'academic_year')},
            },
        ),
    ]
