# Generated by Django 6.0.4 on 2026-05-06 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('credits', models.IntegerField(default=3)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='teacher_email',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='tenant_id',
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education_academics.academicyear'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='class_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='education_academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='education_academics.subject'),
        ),
        migrations.RemoveField(
            model_name='section',
            name='code',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='section',
            name='tenant_id',
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_ref', 'subject')},
        ),
    ]
