# Generated by Django 6.0.5 on 2026-05-12 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0003_teacherdailyavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('on_leave', 'On Leave'), ('absent', 'Absent')], default='present', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='education_academics.teacher')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
