# Generated by Django 6.0.4 on 2026-05-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_add_tenant_nullable'),
        ('education_academics', '0004_teacherattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core_tenants.school'),
        ),
        migrations.AddField(
            model_name='section',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core_tenants.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core_tenants.school'),
        ),
    ]
