# Generated by Django 6.0.4 on 2026-07-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0006_assessmenttype_classroom_gradescale_syllabustopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
