# Generated by Django 6.0.4 on 2026-07-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0007_schoolclass_description_schoolclass_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='classroom',
            name='floor',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
