# Generated by Django 6.0.4 on 2026-07-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0008_classroom_category_classroom_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='education_academics.classroom'),
        ),
    ]
