# Generated by Django 6.0.4 on 2026-07-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0009_schoolclass_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='max_students',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
