# Generated by Django 6.0.5 on 2026-07-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0010_schoolclass_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='father_husband_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='home_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='shift',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
