# Generated by Django 6.0.5 on 2026-07-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0011_teacher_blood_group_teacher_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('class_subject', 'day_of_week', 'period', 'academic_year', 'section')},
        ),
    ]
