# Generated by Django 6.0.4 on 2026-07-15 11:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0016_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacherleave',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timetablesubstitution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
