# Generated by Django 6.0.4 on 2026-07-16 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0017_alter_homework_id_alter_leavebalance_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('meeting_with', models.CharField(choices=[('all', 'All Students'), ('class', 'Select Class'), ('teachers', 'Teachers Only')], default='all', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(default='30 min', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_meetings', to='education_academics.schoolclass')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_meetings', to='education_academics.teacher')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
