# Generated by Django 6.0.4 on 2026-07-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0018_livemeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='marks',
            field=models.IntegerField(default=100),
        ),
    ]
