# Generated by Django 6.0.4 on 2026-07-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0019_classsubject_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
