# Generated by Django 6.0.4 on 2026-07-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0021_homework_max_marks_homeworksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='annual_type_entitlement',
            field=models.IntegerField(default=0, help_text='Annual leave days allowed per year'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='casual_entitlement',
            field=models.IntegerField(default=0, help_text='Casual leave days allowed per year'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='emergency_entitlement',
            field=models.IntegerField(default=0, help_text='Emergency leave days allowed per year'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='maternity_entitlement',
            field=models.IntegerField(default=0, help_text='Maternity leave days allowed per year'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='other_entitlement',
            field=models.IntegerField(default=0, help_text='Other leave days allowed per year'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='sick_entitlement',
            field=models.IntegerField(default=0, help_text='Sick leave days allowed per year'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='annual_entitlement',
            field=models.IntegerField(default=0, help_text='Total leave days allowed per year (legacy combined field)'),
        ),
    ]
