# Generated by Django 6.0.4 on 2026-07-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0022_leavebalance_annual_type_entitlement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherleave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
