# Generated by Django 5.2.17 on 2026-09-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0002_backfill_default_tenant"),
        ("education_academics", "0023_alter_teacherleave_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="assessmenttype",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="gradescale",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="livemeeting",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="teacherleave",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AlterField(
            model_name="assessmenttype",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name="assessmenttype",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_assessmenttype_code_per_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="classroom",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_classroom_code_per_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uniq_subject_code_per_school"
            ),
        ),
    ]
