# Generated by Django 5.2.17 on 2026-09-25 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0003_assign_unowned_rows"),
        ("education_academics", "0024_school_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="grade_level",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="homeroom_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeroom_classes",
                to="education_academics.teacher",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="credit_value",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Credits earned for passing the course, e.g. 1.0 or 0.5",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="department",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_elective",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subject",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Standard"),
                    ("honors", "Honors"),
                    ("advanced", "Advanced"),
                    ("ap", "AP"),
                    ("ib", "IB"),
                    ("remedial", "Support / remedial"),
                ],
                default="standard",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("term", "Term"),
                            ("semester", "Semester"),
                            ("trimester", "Trimester"),
                            ("quarter", "Quarter"),
                        ],
                        default="term",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="education_academics.academicyear",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["academic_year", "order", "start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("academic_year", "name"), name="uniq_term_name_per_year"
                    )
                ],
            },
        ),
    ]
