# Generated by Django 5.2.17 on 2026-09-25 12:22

import django.db.models.deletion
import services.core.tenants.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_tenants", "0003_assign_unowned_rows"),
        ("education_students", "0013_backfill_enrollments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("holiday", "Holiday / no school"),
                            ("meeting", "Meeting"),
                            ("deadline", "Deadline"),
                            ("exam", "Exam period"),
                            ("trip", "Trip"),
                            ("sports", "Sports"),
                            ("other", "Other"),
                        ],
                        default="event",
                        max_length=12,
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, help_text="Empty = all day", null=True
                    ),
                ),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("everyone", "Everyone"),
                            ("staff", "Staff only"),
                            ("families", "Families and students"),
                            ("class", "Chosen classes"),
                            ("grade", "Grade levels"),
                        ],
                        default="everyone",
                        max_length=10,
                    ),
                ),
                ("class_ids", models.JSONField(blank=True, default=list)),
                ("grade_levels", models.JSONField(blank=True, default=list)),
                (
                    "closes_school",
                    models.BooleanField(
                        default=False, help_text="No attendance is taken on these days"
                    ),
                ),
                (
                    "remind_days_before",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("reminder_sent_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "start_time"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MeetingSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Parent-teacher meeting", max_length=120),
                ),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Room, or a video-call link",
                        max_length=200,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                ("booked_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="education_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
    ]
