# Generated by Django 6.0.4 on 2026-05-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardian_email',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, help_text='Complete residential address'),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
