# Generated by Django 6.0.4 on 2026-05-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_academics', '0004_teacherattendance'),
        ('education_students', '0002_student_profile_picture'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='student',
                    name='deleted_at',
                    field=models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE education_students_student '
                        'ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone NULL;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        'CREATE INDEX IF NOT EXISTS education_students_student_deleted_at_idx '
                        'ON education_students_student (deleted_at);'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='education_s_student_f5e5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_class', 'is_active'], name='education_s_current_dde5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['created_at'], name='education_s_created_e26589_idx'),
        ),
    ]
