# Generated by Django 6.0.4 on 2026-05-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_students', '0002_remove_student_guardian_email_student_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='student',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
