# Generated by Django 6.0.4 on 2026-05-16 10:58

import django.db.models.deletion
import services.core.storage.utils
from django.db import migrations, models


def add_tenant_column(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("PRAGMA table_info(education_students_student)")
            columns = [row[1] for row in cursor.fetchall()]
            if 'tenant_id' not in columns:
                cursor.execute('ALTER TABLE education_students_student ADD COLUMN tenant_id varchar(32) NULL;')
    else:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE education_students_student
                DROP COLUMN IF EXISTS tenant_id;
                ALTER TABLE education_students_student
                ADD COLUMN tenant_id uuid NULL;
                ALTER TABLE education_students_student
                ADD CONSTRAINT education_students_student_tenant_id_fk
                FOREIGN KEY (tenant_id) REFERENCES tenants_school(id)
                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            """)

class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_add_tenant_nullable'),
        ('education_students', '0003_db_scalability'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='student',
                    name='tenant',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='students',
                        to='core_tenants.school',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_tenant_column,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=services.core.storage.utils.student_profile_upload_to),
        ),
    ]
