# Generated by Django 6.0.4 on 2026-07-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_students', '0004_add_tenant_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='additional_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
