# Generated by Django 6.0.4 on 2026-07-16 16:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_students', '0006_student_birth_form_id_student_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template', models.CharField(max_length=100)),
                ('recipient_type', models.CharField(choices=[('student', 'Student'), ('employee', 'Employee')], max_length=20)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_id', models.CharField(blank=True, default='', max_length=100)),
                ('recipient_details', models.JSONField(blank=True, default=dict)),
                ('custom_text', models.TextField(blank=True, default='')),
                ('issue_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
