# Generated by Django 5.2.17 on 2026-09-25 06:13

import django.db.models.deletion
import services.core.tenants.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0003_assign_unowned_rows"),
        ("education_students", "0008_school_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="For example: Khan family", max_length=255
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "preferred_language",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("stepmother", "Stepmother"),
                            ("stepfather", "Stepfather"),
                            ("grandparent", "Grandparent"),
                            ("aunt_uncle", "Aunt or uncle"),
                            ("sibling", "Sibling"),
                            ("legal_guardian", "Legal guardian"),
                            ("foster_parent", "Foster parent"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "mobile_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("home_phone", models.CharField(blank=True, default="", max_length=30)),
                ("work_phone", models.CharField(blank=True, default="", max_length=30)),
                (
                    "occupation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("employer", models.CharField(blank=True, default="", max_length=150)),
                (
                    "national_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Only if different from the household",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guardian_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guardians",
                        to="education_students.household",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.AddField(
            model_name="student",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="education_students.household",
            ),
        ),
        migrations.CreateModel(
            name="Immunization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vaccine", models.CharField(max_length=100)),
                ("dose", models.CharField(blank=True, default="", max_length=30)),
                ("date_given", models.DateField(blank=True, null=True)),
                ("exempt", models.BooleanField(default=False)),
                (
                    "exemption_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immunizations",
                        to="education_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["vaccine", "date_given"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StudentHealth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("allergies", models.TextField(blank=True, default="")),
                (
                    "has_severe_allergy",
                    models.BooleanField(
                        default=False, help_text="For example, needs an EpiPen"
                    ),
                ),
                ("medical_conditions", models.TextField(blank=True, default="")),
                ("medications", models.TextField(blank=True, default="")),
                ("dietary_restrictions", models.TextField(blank=True, default="")),
                (
                    "physician_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "physician_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "insurance_provider",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("emergency_treatment_consent", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health",
                        to="education_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Main contact for this student"
                    ),
                ),
                ("lives_with", models.BooleanField(default=True)),
                (
                    "has_custody",
                    models.BooleanField(
                        default=True, help_text="Legal custody; may make decisions"
                    ),
                ),
                (
                    "can_pickup",
                    models.BooleanField(
                        default=True,
                        help_text="Allowed to collect the student from school",
                    ),
                ),
                ("is_emergency_contact", models.BooleanField(default=True)),
                (
                    "receives_billing",
                    models.BooleanField(
                        default=False, help_text="Gets invoices and statements"
                    ),
                ),
                (
                    "receives_messages",
                    models.BooleanField(
                        default=True, help_text="Gets announcements and alerts"
                    ),
                ),
                (
                    "portal_access",
                    models.BooleanField(
                        default=True,
                        help_text="May see this student in the parent portal",
                    ),
                ),
                (
                    "custody_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Court orders or restrictions the office must know about",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Order to call in an emergency"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_links",
                        to="education_students.guardian",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_links",
                        to="education_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "guardian"), name="uniq_student_guardian"
                    )
                ],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
    ]
