# Generated by Django 5.2.17 on 2026-09-25 13:44

import django.db.models.deletion
import services.core.tenants.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0003_assign_unowned_rows"),
        ("education_students", "0013_backfill_enrollments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("report", "Report"),
                            ("certificate", "Certificate"),
                            ("medical", "Medical"),
                            ("identity", "Identity"),
                            ("letter", "Letter"),
                            ("consent", "Consent form"),
                            ("assignment", "Schoolwork"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="student-documents/%Y/%m/")),
                (
                    "original_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                ("visible_to_family", models.BooleanField(default=True)),
                ("from_family", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="education_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
    ]
