# Generated by Django 6.0.4 on 2026-05-16 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_communication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='api_key',
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='template_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='business_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='phone_number_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='webhook_verified',
            field=models.BooleanField(default=False),
        ),
    ]
