# Generated by Django 5.2.17 on 2026-09-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0002_backfill_default_tenant"),
        ("education_communication", "0003_rename_tenant_id_legacy"),
    ]

    operations = [
        # The renamed legacy column kept its old index name (…_tenant_id_…),
        # which the new FK's index needs: drop and recreate it under the new name.
        *[
            op
            for m in ('message', 'notification', 'messagetemplate', 'autotrigger', 'whatsappconfig')
            for op in (
                migrations.AlterField(
                    model_name=m, name='legacy_tenant_code',
                    field=models.CharField(blank=True, max_length=100, db_index=False),
                ),
                migrations.AlterField(
                    model_name=m, name='legacy_tenant_code',
                    field=models.CharField(blank=True, max_length=100, db_index=True),
                ),
            )
        ],
        migrations.AddField(
            model_name="autotrigger",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="whatsappconfig",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
    ]
