# Generated by Django 5.2.17 on 2026-09-26 14:39

import django.db.models.deletion
import services.core.tenants.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0003_assign_unowned_rows"),
        ("education_communication", "0005_messaging_announcements_sms"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="batch",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="dedupe_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="error",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="message",
            name="event",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="smsconfig",
            name="whatsapp_from",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.CreateModel(
            name="AutoTextRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("absent", "Unexcused absence"),
                            ("late", "Late arrival"),
                            ("chronic", "Frequent absence"),
                            ("fee_reminder", "Fee reminder"),
                            ("emergency", "Emergency message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sms", models.BooleanField(default=True)),
                ("whatsapp", models.BooleanField(default=False)),
                ("template", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "event")},
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
    ]
