# Generated by Django 6.0.5 on 2026-05-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_features', '0003_enable_online_payments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='featureflag',
            new_name='core_featur_name_382d66_idx',
            old_name='core_featur_name_6e0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='featureflag',
            new_name='core_featur_is_enab_a2275d_idx',
            old_name='core_featur_is_enab_8f3c2a_idx',
        ),
    ]
