# Generated by Django 5.2.17 on 2026-09-25 20:06

import django.db.models.deletion
import services.core.tenants.mixins
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_tenants", "0003_assign_unowned_rows"),
        ("education_finance", "0015_credits_refunds_stripe"),
        ("education_students", "0015_contact_change_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True, help_text="Item code", max_length=40
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "Pieces"),
                            ("box", "Boxes"),
                            ("pack", "Packs"),
                            ("ream", "Reams"),
                            ("set", "Sets"),
                            ("pair", "Pairs"),
                            ("kg", "Kilograms"),
                            ("litre", "Litres"),
                            ("metre", "Metres"),
                        ],
                        default="pcs",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Store room / shelf",
                        max_length=100,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Warn when stock falls to this",
                        max_digits=12,
                    ),
                ),
                (
                    "reorder_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="How much to order",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Average cost of one unit",
                        max_digits=12,
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price when sold to a student (uniform, books)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("low_alert_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="education_inventory.category",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(db_index=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ordered", "Ordered"),
                            ("partial", "Partly received"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("order_date", models.DateField(blank=True, null=True)),
                ("expected_date", models.DateField(blank=True, null=True)),
                (
                    "supplier_invoice",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The supplier's bill number",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PurchaseLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="education_inventory.item",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="education_inventory.purchaseorder",
                    ),
                ),
            ],
            options={
                "ordering": ["item__name"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="NTN / VAT / tax ID",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="education_inventory.supplier",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="preferred_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="education_inventory.supplier",
            ),
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("returned", "Returned to store"),
                            ("count_up", "Stock count (more)"),
                            ("issued", "Issued"),
                            ("sold", "Sold to a student"),
                            ("damaged", "Damaged / lost"),
                            ("count_down", "Stock count (less)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "issued_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Department, classroom or person",
                        max_length=150,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=100)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education_finance.invoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="education_inventory.item",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
                (
                    "purchase_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="education_inventory.purchaseline",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
                "indexes": [
                    models.Index(
                        fields=["item", "at"], name="education_i_item_id_91f14e_idx"
                    ),
                    models.Index(
                        fields=["kind", "at"], name="education_i_kind_9b0d83_idx"
                    ),
                ],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                fields=("tenant", "number"), name="uniq_purchase_order_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("tenant", "sku"), name="uniq_inventory_sku"
            ),
        ),
    ]
