# Generated by Django 5.2.17 on 2026-09-25 20:35

import django.db.models.deletion
import services.core.tenants.mixins
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_tenants", "0003_assign_unowned_rows"),
        ("education_finance", "0015_credits_refunds_stripe"),
        ("education_students", "0015_contact_change_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "daily_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Set by the family; blank = the school default",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("low_alert_sent", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeteria_account",
                        to="education_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("meal", "Meal"),
                            ("snack", "Snack"),
                            ("drink", "Drink"),
                            ("fruit", "Fruit"),
                            ("dessert", "Dessert"),
                            ("other", "Other"),
                        ],
                        default="meal",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "allergens",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma separated, e.g. nuts, milk, egg, gluten",
                        max_length=255,
                    ),
                ),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_halal", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Lunch every school day", max_length=120
                    ),
                ),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("snack", "Snack"),
                        ],
                        default="lunch",
                        max_length=10,
                    ),
                ),
                ("monthly_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MealPlanMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="education_cafeteria.mealplan",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to="education_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "student__full_name"],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TopUpRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for payment"),
                            ("credited", "Added"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("credited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_up_requests",
                        to="education_cafeteria.account",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cafeteria_top_up",
                        to="education_finance.invoice",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CafeteriaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_daily_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Blank = no limit unless a parent sets one",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "low_balance_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("200"),
                        help_text="Tell the family when the balance falls to this",
                        max_digits=10,
                    ),
                ),
                (
                    "allow_negative",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="How far below zero a student may go (0 = never)",
                        max_digits=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant",), name="uniq_cafeteria_settings"
                    )
                ],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MenuDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("snack", "Snack"),
                        ],
                        default="lunch",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True,
                        related_name="menus",
                        to="education_cafeteria.fooditem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "meal"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "date", "meal"), name="uniq_menu_day"
                    )
                ],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("top_up", "Top-up"),
                            ("purchase", "Purchase"),
                            ("meal_plan", "Meal plan meal"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive adds to the balance, negative takes from it",
                        max_digits=10,
                    ),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("items", models.JSONField(blank=True, default=list)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("invoice", "Invoice / online"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("meal", models.CharField(blank=True, default="", max_length=10)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="education_cafeteria.account",
                    ),
                ),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refund_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="education_cafeteria.transaction",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
                "indexes": [
                    models.Index(
                        fields=["account", "at"], name="education_c_account_bce2bf_idx"
                    ),
                    models.Index(
                        fields=["kind", "at"], name="education_c_kind_925bcd_idx"
                    ),
                ],
            },
            bases=(services.core.tenants.mixins.SchoolAliasMixin, models.Model),
        ),
    ]
