# Generated by Django 6.0.4 on 2026-05-16 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_code', models.CharField(db_index=True, max_length=100)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('bucket_type', models.CharField(choices=[('media', 'Media'), ('backups', 'Backups'), ('reports', 'Reports'), ('public', 'Public')], default='media', max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('related_model', models.CharField(blank=True, max_length=128)),
                ('related_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_code', 'related_model'], name='core_storag_tenant__9f258c_idx'), models.Index(fields=['bucket_type', 'created_at'], name='core_storag_bucket__2bb9b2_idx')],
            },
        ),
    ]
