# Generated by Django 6.0.4 on 2026-05-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_attendance', '0001_initial'),
        ('education_students', '0002_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'date'], name='education_a_student_1eeb25_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['tenant_id', 'date'], name='education_a_tenant__f2f659_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['created_at'], name='education_a_created_18be4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='uniq_attendance_student_date'),
        ),
    ]
