# Generated by Django 6.0.4 on 2026-05-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='course_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
