# Generated by Django 6.0.4 on 2026-05-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0001_add_tenant_nullable'),
        ('education_attendance', '0002_db_scalability'),
        ('education_students', '0004_add_tenant_nullable'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='education_a_tenant__f2f659_idx',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='tenant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attendance_records',
                to='core_tenants.school',
            ),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['tenant', 'date'], name='education_a_tenant__f2f659_idx'),
        ),
    ]
