# Generated by Django 6.0.4 on 2026-06-05 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_attendance', '0005_attendancerecord_marked_by'),
        ('education_students', '0004_add_tenant_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('declining', 'Declining Attendance'), ('weekday', 'Weekday Pattern'), ('consecutive', 'Consecutive Absences'), ('spike', 'Absence Spike'), ('improving', 'Improving Trend'), ('inconsistent', 'Inconsistent Attendance')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('detection_date', models.DateField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('affected_days', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_patterns', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_patterns', to='education_students.student')),
            ],
            options={
                'verbose_name_plural': 'Attendance Patterns',
            },
        ),
        migrations.CreateModel(
            name='AttendanceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_attendance', 'Low Attendance'), ('consecutive_absent', 'Consecutive Absences'), ('weekday_pattern', 'Weekday Pattern Detected'), ('declining', 'Declining Attendance Trend'), ('improvement', 'Attendance Improvement'), ('at_risk', 'Student At Risk')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_alerts', to='education_students.student')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='education_attendance.attendancepattern')),
            ],
            options={
                'verbose_name_plural': 'Attendance Alerts',
            },
        ),
        migrations.CreateModel(
            name='AttendanceAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_records', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('excused_count', models.IntegerField(default=0)),
                ('holiday_count', models.IntegerField(default=0)),
                ('attendance_rate', models.FloatField(default=0.0)),
                ('trend_direction', models.CharField(choices=[('up', 'Improving'), ('down', 'Declining'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('risk_score', models.FloatField(default=0.0)),
                ('has_consecutive_absences', models.BooleanField(default=False)),
                ('consecutive_absence_count', models.IntegerField(default=0)),
                ('has_weekday_pattern', models.BooleanField(default=False)),
                ('declining_trend', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_analytics', to='education_students.student')),
            ],
            options={
                'verbose_name_plural': 'Attendance Analytics',
                'indexes': [models.Index(fields=['student', 'date'], name='education_a_student_baccf3_idx'), models.Index(fields=['date', 'risk_level'], name='education_a_date_c06139_idx'), models.Index(fields=['risk_score', 'date'], name='education_a_risk_sc_5369b4_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='uniq_analytics_student_date')],
            },
        ),
        migrations.AddIndex(
            model_name='attendancepattern',
            index=models.Index(fields=['student', 'is_active'], name='education_a_student_b09b11_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepattern',
            index=models.Index(fields=['pattern_type', 'severity'], name='education_a_pattern_856cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepattern',
            index=models.Index(fields=['detection_date'], name='education_a_detecti_633b89_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancealert',
            index=models.Index(fields=['student', 'is_resolved'], name='education_a_student_c4ff2b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancealert',
            index=models.Index(fields=['alert_type', 'priority'], name='education_a_alert_t_3ffd93_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancealert',
            index=models.Index(fields=['created_at'], name='education_a_created_bc8bee_idx'),
        ),
    ]
