# Generated by Django 6.0.4 on 2026-06-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_attendance', '0006_attendancepattern_attendancealert_and_more'),
        ('education_students', '0004_add_tenant_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to='education_students.student')),
            ],
        ),
    ]
