# Generated by Django 5.2.17 on 2026-09-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0002_backfill_default_tenant"),
        ("education_attendance", "0007_studentfaceencoding"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfaceencoding",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core_tenants.school",
            ),
        ),
    ]
