# Generated by Django 5.2.17 on 2026-09-25 08:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def flag_old_excused(apps, schema_editor):
    Record = apps.get_model('education_attendance', 'AttendanceRecord')
    Record.objects.filter(status='excused').update(is_excused=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core_tenants", "0003_assign_unowned_rows"),
        ("education_academics", "0024_school_tenant"),
        ("education_attendance", "0008_school_tenant"),
        ("education_students", "0011_merge_households_sharing_parent_login"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="is_excused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="minutes_late",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("illness", "Illness"),
                    ("medical", "Medical appointment"),
                    ("family", "Family matter"),
                    ("religious", "Religious observance"),
                    ("school_activity", "School activity"),
                    ("transport", "Transport"),
                    ("unknown", "No reason given"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("late", "Late"),
                    ("excused", "Excused"),
                    ("holiday", "Holiday"),
                    ("early_dismissal", "Early dismissal"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AbsenceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("absent", "Absent all day"),
                            ("late", "Arriving late"),
                            ("early_dismissal", "Leaving early"),
                        ],
                        default="absent",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("illness", "Illness"),
                            ("medical", "Medical appointment"),
                            ("family", "Family matter"),
                            ("religious", "Religious observance"),
                            ("school_activity", "School activity"),
                            ("transport", "Transport"),
                            ("unknown", "No reason given"),
                            ("other", "Other"),
                        ],
                        default="illness",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "submitted_by_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for review"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("response", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_reports",
                        to="education_students.student",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("absent", "Absence"),
                            ("late", "Tardy"),
                            ("early_dismissal", "Early dismissal"),
                            ("chronic", "Frequent absences"),
                            ("report", "Absence report received"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("sent_to", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_notices",
                        to="education_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "date", "kind"),
                        name="uniq_attendance_notice",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PeriodAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("period_number", models.PositiveSmallIntegerField()),
                (
                    "subject_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Tardy"),
                            ("excused", "Excused"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("is_excused", models.BooleanField(default=False)),
                (
                    "minutes_late",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="education_academics.period",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_attendance",
                        to="education_students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core_tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "period_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "date", "period_number"),
                        name="uniq_period_attendance",
                    )
                ],
            },
        ),
        migrations.RunPython(flag_old_excused, migrations.RunPython.noop),
    ]
